name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: cmake
      id: cmake
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: cmake
        setup-command: sudo apt update && sudo apt install cmake libcriterion-dev
        command: "./build.sh -c"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CMAKE_RESULTS: "${{steps.cmake.outputs.result}}"
      with:
        runners: cmake
